### ISSUE TITLE
Static Site Generator

### ISSUE THREAD

**Issue by patrickdavey** [patrickdavey/vimwiki_markdown#1]
Thinking about it, making either a separate binary, or at least an option to allow users to simply say "generate the static site for me" would be a better way to go.  It could optionally plug into `vimwikiAllToHTML` but that would require a code change on vimwiki's side.

Just need to pass a config of the template, site_dir, and then assume ? that any markdown files which are in the wiki directory should be turned into html files.

Really is the cleanest way of doing things I think.

**Comment by RidaAyed** [comment]
@patrickdavey I'm interested in your thoughts considering the vast amount of static generators today. Would you rather have a filewatching static website generator e.g. Hugo these days instead of using vimwikis export2html at all? Looking forward to learn from your experience

**Comment by patrickdavey** [comment]
Hi @RidaAyed , great question. As you can see, I've pretty much done nothing about this one since 2015 ;) . I had a quick look at [hugo](https://gohugo.io), it does look nice. I'd also not seen the [isso](https://posativ.org/isso/) commenting system. Quite tempted to play around with it now, as I really don't like the idea of using `disqus` at all.

Hugo does sound good. It'd be a question of ensuring it can convert the `[[wiki]]` style links correctly, which I assume could be added in somehow. There are a few directives you can pass in `%title` etc. which `hugo` would need to understand too. 

I guess it comes down to: do you want to use this gem and configure that, or, install hugo and tweak it until it works. I suspect `hugo` is the nicer solution overall, but, it's probably more work to get it setup.

If you _do_ take the time to write up how to configure `hugo` to work with `vimwiki`, I'd be totally happy to put up a link etc.

**Comment by patrickdavey** [comment]
No, this isn't a static site generator (well, any more than it is already)
