### ISSUE TITLE
Template Selection

### ISSUE THREAD

**Issue by KTSCode** [patrickdavey/vimwiki_markdown#10]
adding the line
`%template index`
to one of my files does not cause the template _index.tpl_ to be used when generating the HTML for that page. Am I doing something wrong, or is this feature not implemented yet?

**Comment by KTSCode** [comment]
I looked at the code and saw that the functionality I was asking about was not implemented, so I implemented it here https://github.com/patrickdavey/vimwiki_markdown/pull/11

**Comment by patrickdavey** [comment]
Closed in pr #11
