### ISSUE TITLE
Reimplement tags functionality

### ISSUE THREAD

**Issue by patrickdavey** [patrickdavey/vimwiki_markdown#18]
The tags functionality has been removed in https://github.com/patrickdavey/vimwiki_markdown/commit/6852e839d2abac9df532981f995fa40d2ff082d1 originally implemented in https://github.com/patrickdavey/vimwiki_markdown/pull/11

There was an issue I couldn't quickly work around when upgrading to the latest github/markup gem. Also, it didn't play nicely with custom extensions (now implemented) nor with [[wiki links with multiple words in them]]. I've now added covering specs for _some_ of that, and, I think perhaps the functionality can be reimplemented without requiring actually needing to change the _links_ themselves. That is, we can still leave those paramaterized (so they're valid markdown links), but, still put in a custom title.

Well, maybe anyway ;)

If anyone wants to take a shot, esp @KTSCode  go for it, otherwise I'll try to get to it sometime.

**Comment by pcalves** [comment]
It'd be nice to add support to [`%date`](https://github.com/vimwiki/vimwiki/blob/417490f30b3aaec600c19cfa59018cf2368dd87b/doc/vimwiki.txt#L1482-L1491) and [`%nohtml`](https://github.com/vimwiki/vimwiki/blob/417490f30b3aaec600c19cfa59018cf2368dd87b/doc/vimwiki.txt#L1461-L1467) as well. 🙂

**Comment by patrickdavey** [comment]
How're your ruby skills? ;) PRs are welcome (neither date nor nohtml should be that hard to do).  But yes, I'll make some time for it and will add those unless you or anyone else has done it already :)

**Comment by pcalves** [comment]
Pretty much non-existent but I might take that challenge if I can carve some time. 😄

**Comment by patrickdavey** [comment]
@pcalves I pushed out version 0.3.3 with support for `%date%` and `%nohtml` ...

It wasn't totally clear to me from the [%date docs](https://github.com/vimwiki/vimwiki/blob/417490f30b3aaec600c19cfa59018cf2368dd87b/doc/vimwiki.txt#L1482-L1491) that you'd helpfully linked to, whether the closing % was required. I also haven't implemented the ability for someone to have a custom date. Would that be `%date mydate` or `%date mydate%` .. I think for this to work it would really have to be enclosed completely in %'s.

Anyway, specifying a date seems pretty redundant so I think I'll just leave it as is.

Still need to put back the original tagging functionality though.

**Comment by pcalves** [comment]
I'm happy without the custom date, working pretty well on `0.3.3`. 👍

**Comment by patrickdavey** [comment]
Going to close this issue now, happy to take a PR for tags if anyone wants/misses it :)
