### ISSUE TITLE
Broken links in HTML

### ISSUE THREAD

**Issue by pcalves** [patrickdavey/vimwiki_markdown#19]
Hey! First of all, thanks for your hard work on this plugin, I'm a novice user of vimwiki and allowing people to use markdown is pretty cool.

However I'm running into an issue. In my `vimrc` I'm importing your fork of the plugin like this:
```vim
Plug 'patrickdavey/vimwiki-1', { 'branch': 'dev' }
```

Then, I set up my wiki with the following parameters:
```vim
" vimwiki
let g:vimwiki_conceallevel = 0
let g:vimwiki_folding='expr' "this allows the folding to work for markdown

let g:vimwiki_list = [{
  \ 'nested_syntaxes': {
  \   'javascript': 'javascript',
  \   'bash': 'sh',
  \   'vim': 'vim',
  \  },
  \ 'template_default': 'default',
  \ 'syntax': 'markdown',
  \ 'ext': '.md',
  \ 'path': '~/vimwiki/',
  \ 'template_path': '~/vimwiki/templates/',
  \ 'path_html': '~/vimwiki/site_html/',
  \ 'custom_wiki2html': 'vimwiki_markdown',
  \ 'template_ext': '.tpl',
  \ }]
```

In my markdown files, I'm setting up links such as these:
```
# (Neo)vim

Snippets, tips and tricks gathered here and there.

- [Pretty print JSON](Pretty print JSON)
- [Why is pasting long strings slow?](Why is pasting long strings slow?)
```

When I call `:VimwikiAll2HTML`, it generates all the HTML correctly. It renames the links as expected (e.g. `pretty-print-json.html` and `why-is-pasting-long-strings-slow.html`.

However, it doesn't appear to be renaming the HTML files themselves. I end up with `Pretty print JSON.html` and `Why is pasting long strings slow?.html` and, therefore, broken links in the index page.

Am I missing something in the configuration? I installed the gem without issues and the extension seems to be working fine otherwise. Apologies if I'm missing something completely obvious. Let me know if you need anything else to help uncover the culprit.

**Comment by patrickdavey** [comment]
Damn... you're totally right. Not sure how I managed to completely break that :(

I'll look into it - it might be a few days before I get it fixed. How annoying!

Thanks for raising this issue.

**Comment by patrickdavey** [comment]
@pcalves I've released version 0.3.2, can you update and see if it fixes the links.

You'll probably have to remove all the previously generated html files for this to work. Also, I suggest you use the main `vimwiki` vim-plugin, not my fork. Unfortunately this means that the re-generation of files is _a bit slower than it might be_ because of how the files are named, but, at least it'll be correct.

Can you let me know if this latest version fixes your issue.

I'm just sad that everyone else must have been affected and either not noticed / not been bothered to open an issue!! so, thank you very much for alerting me! 👍

**Comment by pcalves** [comment]
That was fast! Updated & tested, everything is working perfectly now. Tested with both your fork and the official plugin, both worked without a hitch. Thank you very much for jumping on this so quickly.

> I'm just sad that everyone else must have been affected and either not noticed / not been bothered to open an issue!! so, thank you very much for alerting me! 👍

Maybe people just don't update their gems too often? I know I sure don't 😅 In any case, you're welcome, and thanks again for getting the fix out so quickly.

**Comment by patrickdavey** [comment]
Thanks @pcalves  - closing this.
