### ISSUE TITLE
Not working..

### ISSUE THREAD

**Issue by jcguu95** [patrickdavey/vimwiki_markdown#21]
# What I have done
1. Installed the latest ruby.
2. Install vimwiki_markdown via ruby.
3. Add "let g:vimwiki_list = ..." as shown in the readme.md to my .vimrc
4. Open my vimwiki index.md, and execute "Vimwiki2HTML"
5. Still got the same error: Vimwiki Error: Conversion to HTML is not supported for this syntax.

**Comment by patrickdavey** [comment]
Can you read through the comments in https://github.com/patrickdavey/vimwiki_markdown/issues/9 please - especially https://github.com/patrickdavey/vimwiki_markdown/issues/9#issuecomment-491617704

That error is coming from _vimwiki_ because when it tries to shell out to vimwiki_markdown it can't find the binary. At least, I'm pretty sure that's the issue.

**Comment by jcguu95** [comment]
It works! Thank you @patrickdavey. My issue is exactly @NikosAlexandris's (in the comment)! I followed what he did, and "$ gem install rdoc" twice (since it warned my "rdoc" is not loadable, and it works! (I haven't used ruby before.. so not quite sure why it did not work the first time I "$ gen install rdoc".

**Comment by patrickdavey** [comment]
Glad it's working for you :) ruby can be a little tricky install wise. I tend to use https://rvm.io/ which, while a little heavy, does seem to make a lot of these kind of dependency issues vanish.

**Comment by jcguu95** [comment]
Thank you for your amazing script! I can now make minimal websites like a breeze!

**Comment by patrickdavey** [comment]
You're welcome - it has it's place! there are other options more specifically for websites - like https://jekyllrb.com/ which may be more targeted to what you're after... Anyway - great that you can do what you want to do 👍

**Comment by jcguu95** [comment]
Wow! That looks like an amazing option! I should get familiar with ruby.. seems there're lots of awesome programs written in that
