### ISSUE TITLE
Allow raw HTML

### ISSUE THREAD

**Issue by bmedicke** [patrickdavey/vimwiki_markdown#22]
I routinely use HTML in my wikis (to embed YouTube videos, canvases, etc.). 

Unfortunately it gets replaced by the string `<!-- raw HTML omitted -->`. 

As far as I can tell this can be adjusted by passing the `UNSAFE` option to  commonmarker (but I'm not sure how to accomplish that).

Would it be possible to allow html tags by default or add an option for that?

**Comment by patrickdavey** [comment]
Yip, I actually looked at that when I last upgraded the dependencies on `vimwiki_markdown`. From memory, commonmarker didn't expose a way to set `UNSAFE` at the time.

The markup gem now supports the commonmarker options, so, I've upgraded `vimwiki_markdown` and pushed out 0.4.0. So, upgrade `vimwiki_markdown` and it _should_ allow your HTML now @bmedicke . Let me know if you run into issues.

**Comment by bmedicke** [comment]
Thanks for the fast update. The html does make it through but it is entity encoded.

`&lt;iframe width="560" height="315" src="" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;`

**Comment by patrickdavey** [comment]
Hmmm, I only tested against the `<p>` tag - which is passed through OK. Looks like there's a `tagfilter` option which disallows certain tags - of which iframe is one, see the tagfilter here -> https://github.com/gjtorikian/commonmarker#extensions . 

No idea how to turn that off yet, I'll have a look when I have time.. not _sure_ there's an easy way.

**Comment by patrickdavey** [comment]
So the line that allows us to override it https://github.com/github/markup/commit/d3430c3f453546d9291a59c31539aa6233ebae2f hasn't been released yet. Once github-markdown releases a new version then I'll be able to turn off the escaping of all tags. Until then, fresh outa luck (unless you want to manually edit the ruby files yourself)

**Comment by patrickdavey** [comment]
I thought of a way to (nastily) hack my way around the issue, seems to work. I've released 0.4.1, should allow your iframe tags now @bmedicke
