### ISSUE TITLE
initialize: No such file or directory

### ISSUE THREAD

**Issue by arozehnal** [patrickdavey/vimwiki_markdown#31]
I'm totally newbie to vimwiki, probably I did something wrong :-(

I run Vim 8.2 and vimwiki on Windows 10,
I have a few *md file in my first vimwiki:
c:\Users\RO\vimwiki>ls -l
-rw-rw-r--    1 RO       RO              12 Nov 06 20:57 Tasks.md
-rw-rw-r--    1 RO       RO            1716 Nov 09 20:31 VimWiki.md
-rw-rw-r--    1 RO       RO             306 Nov 08 17:17 Zkratky.md
-rw-rw-r--    1 RO       RO            2084 Nov 09 20:52 index.md
drwxrwxr-x    2 RO       RO               0 Nov 09 20:20 site_html
drwxrwxr-x    2 RO       RO               0 Nov 09 20:14 templates

c:\Users\RO\vimwiki>ls -l templates
-rw-rw-r--    1 RO       RO            4001 Nov 09 20:14 default.tpl

====================
from  my .vimrc:
```
let g:vimwiki_list = [{'path': '~/vimwiki', 'template_path': '~/vimwiki/templates/',
          \ 'template_default': 'default', 'syntax': 'markdown', 'ext': '.md',
          \ 'path_html': '~/vimwiki/site_html/', 'custom_wiki2html': 'vimwiki_markdown',
          \ 'html_filename_parameterization': 1,
          \ 'template_ext': '.tpl'}]
```
====================
When I run Vimwiki2HTML for currently open wiki file  I get this
![rb_vimwiki_md](https://user-images.githubusercontent.com/8810398/98590538-42400a80-22cf-11eb-957c-b2176285d75c.jpg)

Any suggestion?

**Comment by patrickdavey** [comment]
Hmmm, sorry, no idea I'm afraid (and I don't even have a windows box to test it out on). My only suggestion would be to try change the paths from `~/vimwiki` etc. to a hard-coded path (probably `C:\Users\RO\vimwiki` etc.)

Other than that, no idea I'm afraid.

**Comment by patrickdavey** [comment]
Did you ever get this sorted @arozehnal  ? I'm going to close this issue as I suspect it's a config option (and I don't have a windows box to test on)
