### ISSUE TITLE
Error installing vimwiki_markdown

### ISSUE THREAD

**Issue by MahbubAlam231** [patrickdavey/vimwiki_markdown#33]
I am getting this error when I run `sudo gem install vimwiki_markdown`. I don't understand any of this error message. Help would be appreciated.

```
Building native extensions. This could take a while...
ERROR:  Error installing vimwiki_markdown:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.7.0/gems/commonmarker-0.21.2/ext/commonmarker
/usr/bin/ruby2.7 -I /usr/lib/ruby/2.7.0 -r ./siteconf20210416-43753-110lyl4.rb extconf.rb
creating Makefile

current directory: /var/lib/gems/2.7.0/gems/commonmarker-0.21.2/ext/commonmarker
make "DESTDIR=" clean

current directory: /var/lib/gems/2.7.0/gems/commonmarker-0.21.2/ext/commonmarker
make "DESTDIR="
compiling arena.c
arena.c:1:10: fatal error: stdlib.h: No such file or directory
    1 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:245: arena.o] Error 1

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.7.0/gems/commonmarker-0.21.2 for inspection.
Results logged to /var/lib/gems/2.7.0/extensions/x86_64-linux/2.7.0/commonmarker-0.21.2/gem_make.out
```

This is the message I get when search for `vimwiki_markdown` in my computer: [searching for vimwiki_markdown](https://drive.google.com/file/d/1_OcEoezx1uB9VKIEn64LLKhkskrNEx36/view?usp=sharing).

**Comment by patrickdavey** [comment]
`arena.c:1:10: fatal error: stdlib.h: No such file or directory` is the thing you're missing. You can try googling for that and see what pops up. It looks like you need to install some command line tools first - https://www.embarcadero.com/starthere/xe5/mobdevsetup/ios/en/installing_the_commandline_tools.html might get you started.

Also, as [suggested in the README](https://github.com/patrickdavey/vimwiki_markdown#install-issues) if you're having install issues, first try installing `rvm` as that often sorts out all your dependencies automagically.

Good luck, I can't really help further, if you get it fixed please add a comment here letting me know what worked.
