### ISSUE TITLE
Markdown directory links

### ISSUE THREAD

**Issue by has2k1** [patrickdavey/vimwiki_markdown#4]
Directory links are not processed accurately.

For example,

```markdown
[anchor-text](directory/)
```
creates a link to `directory.html` instead of a link to one of the following:

1. `directory/` 
2. `directory/index.html`.

I think the second form is better since some browsers show a directory listing when pointed to a local directory root.

Thanks for this, it makes Vimwiki irresistible.

**Comment by patrickdavey** [comment]
Good catch :)

I'll make time for this in the next few weeks (will be busy over Christmas). If you want to send a Pull Request with the change (and a test to cover it) then that's also welcome.

However, I think that the directory link should go to `directory/` not `directory/index.html`, there might be local links, it could be on a server running `php` ;) etc.

**Comment by has2k1** [comment]
I had not considered the use-case explosion that happens when the HTML is served by a real server, and that it makes for a decent blog system. 

Maybe taking a hint from the `g:vimwiki_dir_link` option would lead to the least surprises i.e. the same navigation in `vim` as in `html`, this would require the `wiki` link at the top of the "index" page to go up one-level. If that is not possible then `directory/` is fine.

Sorry I cannot do a PR, as yet I do not know how to work my way around Ruby.
