### ISSUE TITLE
Turn off pygments feature?

### ISSUE THREAD

**Issue by sdondley** [patrickdavey/vimwiki_markdown#41]
I'm going to use js for syntax highlighting. There's no easy way to disable pygments?

**Comment by patrickdavey** [comment]
That's correct, there's no easy way to disable pygments, this gem basically uses the github markdown pipeline and I'm not planning on customizing it to allow swapping out of the various pipelines. 

You can fork the gem of course, you'll probably want to just pull out [this line](https://github.com/patrickdavey/vimwiki_markdown/blob/master/lib/vimwiki_markdown/wiki_body.rb#L25)

If you want to submit a PR complete with tests allowing the various pipelines to be switched out then I'd be open to merging that in.

Also, I think you should close this issue -> https://github.com/vimwiki/vimwiki/issues/1205 as I'm assuming the fix I gave you on this issue that you raised https://github.com/patrickdavey/vimwiki_markdown/issues/39 fixed your issue (you never responded so I can't tell)

**Comment by sdondley** [comment]
Thanks.

And https://github.com/vimwiki/vimwiki/issues/1205 is still a problem.

I tried your markdown code, it didn't work. I'll post there shortly.

**Comment by sdondley** [comment]
I could do a fork, but I have no earthly idea how to write tests with vim.

**Comment by patrickdavey** [comment]
The tests would be in `ruby` not vim.

I do not have time to write this feature, nor is it a priority (or really direction) I want to take this gem in. Therefore I am going to close this issue. If you want to submit a PR with tests with the feature you want then I will be open to merging it.

**Comment by sdondley** [comment]
Commenting out that line didn't work. I'm just going to process the output file post hoc. Can't waste any more time on this.
