### ISSUE TITLE
Pygment styles

### ISSUE THREAD

**Issue by mattyrc** [patrickdavey/vimwiki_markdown#45]
I've been adding css to my default.tpl template to render the html pages in a darker scheme that's easier on the eyes. Unfortunately I have not been able to figure out how to make the pygments code dark.

Would it be possible to use different styles for the pygments?

Thanks

**Comment by patrickdavey** [comment]
Looks like the dependency we use -> https://github.com/rouge-ruby/rouge has some options for `:dark` handling.  It'd require a config option etc. to be passed in.

Do you want to give this a go as a PR (especially if you're a ruby dev!)?  If not I'll try make time for having a play with it in the next week or so :)

**Comment by mattyrc** [comment]
Thanks for the quick response! Unfortunately I don't know very much about ruby development at all or else I'd give this a try.

**Comment by patrickdavey** [comment]
I have added support for dark mode.

Change your template to have `%dark_pygments%` instead of just `%pygments%` and it should work. You'll need to upgrade to the latest gem `0.9.0`

Let me know how you get on @mattyrc

**Comment by mattyrc** [comment]
@patrickdavey 

It's working great! Thank you very much for adding this so quickly.

It took me a minute to realize that both `%pygments%` and `%dark_pygments%` need to be present in the template file.

Cheers!

**Comment by patrickdavey** [comment]
It shouldn't require both? I just tested it out locally and it worked fine for me? What happens if you remove `%pygments%` and just leave `%dark_pygments%` ? in what way is it broken?

**Comment by mattyrc** [comment]
When `%dark_pygments%` only is in the template I am seeing no color in the fenced code block.

I double verified that I am using version 0.9.0 and tested in both Firefox and Chromium.

I've just tried editing the default.tpl from the example_files in three different way and this is what I'm seeing in the html:

`%dark_pygments%` Only:
![darkpyg_only](https://user-images.githubusercontent.com/3344929/229332981-072034c4-79ee-4134-9d90-b583403a64a1.png)

`%pygments%` Only:
![pyg_only](https://user-images.githubusercontent.com/3344929/229332999-015b3b37-2fca-4586-8959-7897b28c13bb.png)

`%pygments%` and `%dark_pygments%`:
![pyg_and_darkpyg](https://user-images.githubusercontent.com/3344929/229333019-7ae2867f-a467-44d6-931e-15e724962978.png)

Markdown. Note I had to remove backticks in markdown because it would mess up GitHubs code block:
```md
**Java Code**
java  
class test {  
  public static void main(String args[]) {
    System.out.println("Hi);  
  }  
}  
  
**Bash Code**  
sh
echo "Enter Your Name"
read name
echo "Welcome $name"
```

**Comment by patrickdavey** [comment]
Doh! Thanks @mattyrc - I've pushed up 0.9.1 which should fix that issue. You should only need `%dark_pygments%` in there now!  Thanks for letting me know :)

**Comment by mattyrc** [comment]
@patrickdavey I can confirm that it is working with only `%dark_pygments%` in version 0.9.1.

Thanks again!
