### ISSUE TITLE
links are not processed correctly when listed on same line as another link

### ISSUE THREAD

**Issue by s317** [patrickdavey/vimwiki_markdown#5]
**Scenario**: Links are placed beside each other

When inks are placed beside each other... the last link (done.md) gets converted to a file with .html extension (done.html) while all other files 1backlog.md, 2todo.md, 3doing.md gets converted to html files but their URLS don't

Markdown:   

```markdown
[1backlog](1backlog) [2todo](2todo)  [3doing](3doing) [4done](4done)
```
HTML Result:

```html
<p><a href="1backlog">1backlog</a> <a href="2todo">2todo</a>  <a href="3doing">3doing</a> <a href="4done.html">4done</a>  </p>
```
However...

Scenario: Links are listed with one link per line, the conversion works.

Markdown:

```markdown
- [1backlog](1backlog)
- [2todo](2todo)
- [3doing](3doing)
- [4done](4done)
```

HTML Result:

```html
<ul>
<li> <a href="1backlog.html">1backlog</a> </li>
<li> <a href="2todo.html">2todo</a><br> </li>
<li> <a href="3doing.html">3doing</a> </li>
<li> <a href="4done.html">4done</a> </li>
</ul>
```

**Comment by patrickdavey** [comment]
Thanks for catching that @s317 . I've fixed it and pushed up a new version.
